### ISSUE TITLE
Can not include Prebid v1.12 via Carthage

### ISSUE THREAD

**Issue by marcelklinek** [prebid/prebid-mobile-ios#399]
I have a library that ships `prebid-mobile-ios` as a dependency. In Cartfile I include Prebid like this:

```
github "prebid/prebid-mobile-ios" == 1.11.0
```

Then I install and build Prebid using 

```
carthage update --use-xcframeworks --platform ios
```

Finally I drag `.xcframework` to the project in General > Frameworks, Libraries, and Embedded Content. This works fine for 1.11.0. When I upgrade to 1.12.0 I can not build the app. This is the error I get:

```
Undefined symbols for architecture x86_64:
  "PrebidMobile.Prebid.shared.unsafeMutableAddressor : PrebidMobile.Prebid", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of generic specialization <YieldloveAdIntegration.PrebidAdUnitFactory> of function signature specialization <Arg[1] = Existential To Protocol Constrained Generic> of YieldloveAdIntegration.PrebidServerBidAdapter.init(requestData: __C.GAMRequest, adUnitFactory: YieldloveAdIntegration.PrebidAdUnitFactoryProtocol) -> YieldloveAdIntegration.PrebidServerBidAdapter in YieldloveAdIntegration(Yieldlove.o)
      function signature specialization <Arg[0] = Owned To Guaranteed> of YieldloveAdIntegration.PrebidAdUnitFactory.init(accountId: Swift.String) throws -> YieldloveAdIntegration.PrebidAdUnitFactory in YieldloveAdIntegration(PrebidAdUnitFactory.o)
  "PrebidMobile.Targeting.shared.unsafeMutableAddressor : PrebidMobile.Targeting", referenced from:
      YieldloveAdIntegration.Yieldlove.init() -> YieldloveAdIntegration.Yieldlove in YieldloveAdIntegration(Yieldlove.o)
      function signature specialization <Arg[1] = Dead> of YieldloveAdIntegration.Yieldlove.(applyTargeting in _D9E475DE415831F495BBF24D0AAEA7A9)(adUnitData: YieldloveExternalConfiguration.ConfigurableAdUnitData) -> () in YieldloveAdIntegration(Yieldlove.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
Undefined symbol: PrebidMobile.Prebid.shared.unsafeMutableAddressor : PrebidMobile.Prebid
Undefined symbol: PrebidMobile.Targeting.shared.unsafeMutableAddressor : PrebidMobile.Targeting
```

Could you point out what are we doing wrong? I understand there were changes in module structure and a change in way you build framework, but can’t figure this out on my own. Thanks!

Prebid 1.12 works fine when installed through CocoaPods.

**Comment by marcelklinek** [comment]
This only happens when we build a Carthage package using dependencies we previously installed using CocoaPods (we ship both). We found out that when we build a Carthage package after installing dependencies using Carthage, all works fine, so I no longer think this is an issue with `prebid-mobile-ios`
